# Generated by Django 2.2.4 on 2019-08-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_amount_of_kilometers',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
    ]
