# Generated by Django 2.2.4 on 2019-08-29 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190820_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_mod_date', models.DateField(auto_now=True)),
                ('distance', models.DecimalField(decimal_places=1, max_digits=4)),
                ('start_name', models.CharField(max_length=200)),
                ('destination_name', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
