# Generated by Django 2.2.4 on 2019-08-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190830_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='end_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
